Repository konveyor/move2kube-demos, pull requests merged in 2021-12, with the labels that each got.

#69 ci: make this repo part of the release workflow
  .github/workflows/release.yml
  releasenotes-config.js
Labels: ci

#70 feat: Add Rust sample with Rocket web framework
  samples/language-platforms/rust/Cargo.toml
  samples/language-platforms/rust/Rocket.toml
  samples/language-platforms/rust/src/main.rs
Labels: feat

#71 fix: update samples to respond to all paths and update language-platforms.zip
  samples/language-platforms.zip
  samples/language-platforms/golang/main.go
  samples/language-platforms/nodejs/main.js
  samples/language-platforms/nodejs/package.json
  samples/language-platforms/php/index.php
  samples/language-platforms/php/site.conf
  samples/language-platforms/python/main.py
  samples/language-platforms/ruby/ruby.rb
  samples/language-platforms/rust/src/main.rs
Labels: fix

#74 fix: Update cfapps.yaml with new move2kube collect output
  samples/cloud-foundry/cfapps.yaml
  samples/cloud-foundry/cluster.yaml
Labels: fix

#82 feat: add config file for e2e-demo app
  samples/enterprise-app/config/m2kconfig.yaml
Labels: feat

#83 fix: the config file for demo purpose
  samples/enterprise-app/config/m2kconfig.yaml
Labels: fix

#84 fix: remove the .dockerignore to avoid problems with COPY inside Dockerfile
  samples/enterprise-app/src.zip
  samples/enterprise-app/src/inventory/.dockerignore
Labels: fix

#85 fix: Remove the .dockerignore files from dotnet5 samples
  samples/dotnet5/dotnet5angular/.dockerignore
  samples/dotnet5/dotnet5react-redux/.dockerignore
  samples/dotnet5/dotnet5react/.dockerignore
  samples/dotnet5/dotnet5webapp/.dockerignore
Labels: fix
