Repository konveyor/move2kube-demos, pull requests merged in 2022-01, with the labels that each got.

#86 chore: add a zip file for the docker compose samples
  samples/docker-compose.zip
Labels: chore

#87 fix: fix empty VCAP in cf apps
  samples/enterprise-app/collect/cf.zip
  samples/enterprise-app/collect/cf/cfapps.yaml
Labels: fix

#88 chore: update the docker compose sample to run properly on clusters
  samples/docker-compose.zip
  samples/docker-compose/m2kqacache.yaml
  samples/docker-compose/multiple-services/api/index.js
  samples/docker-compose/multiple-services/docker-compose.yaml
  samples/docker-compose/multiple-services/web/fib.php
Labels: chore

#89 feat: Upgrades to match m2k v3
  samples/cloud-foundry/cfapps.yaml
Labels: feat

#90 fix: the java-gradle sample was failing because of broken gretty plugin
  samples/language-platforms/java-gradle/.gitignore
  samples/language-platforms/java-gradle/Makefile
  samples/language-platforms/java-gradle/README.md
  samples/language-platforms/java-gradle/build.gradle
  samples/language-platforms/java-gradle/gradle/wrapper/gradle-wrapper.jar
  samples/language-platforms/java-gradle/gradle/wrapper/gradle-wrapper.properties
  samples/language-platforms/java-gradle/gradlew
  samples/language-platforms/java-gradle/gradlew.bat
  samples/language-platforms/java-gradle/settings.gradle
  samples/language-platforms/java-gradle/src/main/java/com/myuser/MyServlet.java
  samples/language-platforms/java-gradle/src/main/java/simplewebapp/MainServlet.java
  samples/language-platforms/java-gradle/src/main/webapp/WEB-INF/web.xml
  samples/language-platforms/java-gradle/usage.png
Labels: fix

#92 fix: Anonymize the m2k_collect info
  samples/cloud-foundry/cfapps.yaml
  samples/cloud-foundry/cluster.yaml
  samples/enterprise-app/collect/k8s/cluster.yaml
  samples/unified-flow/cfnodejs/manifest.yml
  samples/unified-flow/cfnodejs/package.json
  samples/unified-flow/m2k_collect/cfapps.yaml
  samples/unified-flow/m2k_collect/cluster.yaml
Labels: fix

#93 chore: update java-maven and java-gradle samples, remove outdated samples
  .gitignore
  samples/language-platforms.zip
  samples/language-platforms/java-gradle/.gitignore
  samples/language-platforms/java-gradle/src/main/java/com/myuser/MyServlet.java
  samples/language-platforms/java-maven/.gitignore
  samples/language-platforms/java-maven/pom.xml
  samples/language-platforms/java-maven/src/main/webapp/WEB-INF/web.xml
  samples/language-platforms/java-maven/src/main/webapp/index.jsp
  samples/unified-flow/.m2kignore
  samples/unified-flow/cfnodejs/main.js
  samples/unified-flow/cfnodejs/manifest.yml
  samples/unified-flow/cfnodejs/package-lock.json
  samples/unified-flow/cfnodejs/package.json
  samples/unified-flow/docker-compose.yaml
  samples/unified-flow/java-gradle/build.gradle
  samples/unified-flow/java-gradle/src/main/java/simplewebapp/MainServlet.java
  samples/unified-flow/java-gradle/src/main/webapp/WEB-INF/web.xml
  samples/unified-flow/k8syamls/nodejs-deployment.yaml
  samples/unified-flow/k8syamls/nodejs-ingress.yaml
  samples/unified-flow/k8syamls/nodejs-service.yaml
  samples/unified-flow/m2k_collect/cfapps.yaml
  samples/unified-flow/m2k_collect/cluster.yaml
Labels: chore

#97 fix: serve the java-maven sample under / at least on Tomcat and WildFly
  samples/language-platforms.zip
  samples/language-platforms/java-maven/pom.xml
Labels: fix

#100 fix: add schema information to web.xml to avoid validation errors in Liberty server
  samples/language-platforms.zip
  samples/language-platforms/java-gradle/src/main/webapp/WEB-INF/web.xml
  samples/language-platforms/java-maven/src/main/webapp/WEB-INF/web.xml
Labels: fix

#101 chore: remove service that uses quarkus from the e2e-demo, minor changes to the other samples
  samples/enterprise-app/config/m2kconfig.yaml
  samples/enterprise-app/src.zip
  samples/enterprise-app/src/README.md
  samples/enterprise-app/src/customers-tomcat-legacy/.gitignore
  samples/enterprise-app/src/customers-tomcat-legacy/Makefile
  samples/enterprise-app/src/customers-tomcat-legacy/pom.xml
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/OrderManagementAppInitializer.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/config/PersistenceConfig.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/config/WebConfig.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/controller/CustomerController.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/exception/ResourceNotFoundException.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/exception/handler/ExceptionHandlingController.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/model/Customer.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/repository/CustomerRepository.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/java/io/konveyor/demo/ordermanagement/service/CustomerService.java
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/resources/import.sql
  samples/enterprise-app/src/customers-tomcat-legacy/src/main/resources/persistence.properties
  samples/enterprise-app/src/docs/images/architecture.jpg
  samples/enterprise-app/src/docs/images/architecture.png
  samples/enterprise-app/src/frontend/.gitignore
  samples/enterprise-app/src/inventory/.gitignore
  samples/enterprise-app/src/inventory/.mvn/wrapper/MavenWrapperDownloader.java
  samples/enterprise-app/src/inventory/.mvn/wrapper/maven-wrapper.jar
  samples/enterprise-app/src/inventory/.mvn/wrapper/maven-wrapper.properties
  samples/enterprise-app/src/inventory/README.md
  samples/enterprise-app/src/inventory/mvnw
  samples/enterprise-app/src/inventory/mvnw.cmd
  samples/enterprise-app/src/inventory/pom.xml
  samples/enterprise-app/src/inventory/src/main/docker/Dockerfile.jvm
  samples/enterprise-app/src/inventory/src/main/docker/Dockerfile.native
  samples/enterprise-app/src/inventory/src/main/java/io/konveyor/demo/inventory/controller/ProductController.java
  samples/enterprise-app/src/inventory/src/main/java/io/konveyor/demo/inventory/exception/ResourceNotFoundException.java
  samples/enterprise-app/src/inventory/src/main/java/io/konveyor/demo/inventory/exception/handler/ResourceNotFoundExceptionHandler.java
  samples/enterprise-app/src/inventory/src/main/java/io/konveyor/demo/inventory/model/Product.java
  samples/enterprise-app/src/inventory/src/main/java/io/konveyor/demo/inventory/repository/ProductRepository.java
  samples/enterprise-app/src/inventory/src/main/java/io/konveyor/demo/inventory/service/IProductService.java
  samples/enterprise-app/src/inventory/src/main/java/io/konveyor/demo/inventory/service/ProductService.java
  samples/enterprise-app/src/inventory/src/main/resources/application.yml
  samples/enterprise-app/src/inventory/src/main/resources/load.sql
  samples/enterprise-app/src/inventory/src/test/java/io/konveyor/demo/inventory/controller/ProductControllerTest.java
  samples/enterprise-app/src/inventory/src/test/java/io/konveyor/demo/inventory/service/ProductServiceTest.java
  samples/language-platforms.zip
  samples/language-platforms/java-gradle-war/java-gradle-war.war
  samples/language-platforms/java-gradle/build.gradle
  samples/language-platforms/java-maven-war/java-maven-war.war
  samples/language-platforms/java-maven/pom.xml
  samples/language-platforms/java-war/java-war.war
Labels: chore

#102 chore: cleanup customers app
  samples/enterprise-app/src.zip
  samples/enterprise-app/src/customers-tomcat/.gitignore
  samples/enterprise-app/src/customers-tomcat/Makefile
  samples/enterprise-app/src/customers-tomcat/pom.xml
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/OrderManagementAppInitializer.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/config/PersistenceConfig.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/config/WebConfig.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/controller/CustomerController.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/exception/ResourceNotFoundException.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/exception/handler/ExceptionHandlingController.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/model/Customer.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/repository/CustomerRepository.java
  samples/enterprise-app/src/customers-tomcat/src/main/java/io/konveyor/demo/ordermanagement/service/CustomerService.java
  samples/enterprise-app/src/customers-tomcat/src/main/resources/import.sql
  samples/enterprise-app/src/customers-tomcat/src/main/resources/persistence.properties
Labels: chore

#105 chore: moved presentation to website
  presentations/Konveyor Move2Kube - Overview.pdf
Labels: chore

#106 chore: cleanup cf sample and remove zip files
  samples/cloud-foundry/cfnodejsapp/main.js
  samples/cloud-foundry/cfnodejsapp/manifest.yml
  samples/cloud-foundry/cfnodejsapp/package-lock.json
  samples/cloud-foundry/cfnodejsapp/package.json
  samples/cloud-foundry/cluster.yaml
  samples/cloud-foundry/m2k_collect/cf/cfapps.yaml
  samples/docker-compose.zip
  samples/enterprise-app/collect/cf.zip
  samples/enterprise-app/collect/k8s.zip
  samples/enterprise-app/src.zip
  samples/language-platforms.zip
Labels: chore

#108 chore: rename customers-tomcat app as customers
  samples/enterprise-app/config/m2kconfig.yaml
  samples/enterprise-app/src/customers/.gitignore
  samples/enterprise-app/src/customers/Makefile
  samples/enterprise-app/src/customers/pom.xml
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/OrderManagementAppInitializer.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/config/PersistenceConfig.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/config/WebConfig.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/controller/CustomerController.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/exception/ResourceNotFoundException.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/exception/handler/ExceptionHandlingController.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/model/Customer.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/repository/CustomerRepository.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/service/CustomerService.java
  samples/enterprise-app/src/customers/src/main/resources/import.sql
  samples/enterprise-app/src/customers/src/main/resources/persistence.properties
Labels: chore

#109 feat: WCF sample service for dot net legacy demos
  samples/wcfservice/.gitignore
  samples/wcfservice/wcfservice.sln
  samples/wcfservice/wcfservice/App.config
  samples/wcfservice/wcfservice/IWindowsSampleService.cs
  samples/wcfservice/wcfservice/Properties/AssemblyInfo.cs
  samples/wcfservice/wcfservice/WindowsSampleService.cs
  samples/wcfservice/wcfservice/wcfservice.cs
  samples/wcfservice/wcfservice/wcfservice.csproj
Labels: feat

#110 fix: customers and orders services, add profiles to customers service
  samples/enterprise-app/src/customers/.gitignore
  samples/enterprise-app/src/customers/.mvn/wrapper/maven-wrapper.properties
  samples/enterprise-app/src/customers/README.md
  samples/enterprise-app/src/customers/mvnw
  samples/enterprise-app/src/customers/mvnw.cmd
  samples/enterprise-app/src/customers/pom.xml
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/customers/Application.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/customers/controller/CustomerController.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/customers/exception/ResourceNotFoundException.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/customers/exception/handler/ExceptionHandlingController.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/customers/model/Customer.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/customers/repository/CustomerRepository.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/customers/service/CustomerService.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/OrderManagementAppInitializer.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/config/PersistenceConfig.java
  samples/enterprise-app/src/customers/src/main/java/io/konveyor/demo/ordermanagement/config/WebConfig.java
  samples/enterprise-app/src/customers/src/main/resources/application-local.properties
  samples/enterprise-app/src/customers/src/main/resources/application-openshift.properties
  samples/enterprise-app/src/customers/src/main/resources/persistence.properties
  samples/enterprise-app/src/orders/.gitignore
  samples/enterprise-app/src/orders/.mvn/wrapper/maven-wrapper.properties
  samples/enterprise-app/src/orders/README.md
  samples/enterprise-app/src/orders/mvnw
  samples/enterprise-app/src/orders/mvnw.cmd
  samples/enterprise-app/src/orders/pom.xml
Labels: fix

#112 fix: fix broken tutorials link
  README.md
Labels: fix

#113 fix: Update the cfapps.yaml files
  samples/cloud-foundry/m2k_collect/cf/cfapps.yaml
  samples/enterprise-app/collect/cf/cfapps.yaml
Labels: fix
